# Generated by Django 5.1.6 on 2025-02-28 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 11, 14, 56, 357987, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
