# Generated by Django 5.1.6 on 2025-03-11 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordreset_expiration_time_passwordreset_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 16, 21, 1, 898762, tzinfo=datetime.timezone.utc)),
        ),
    ]
