# Generated by Django 5.1.6 on 2025-03-11 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_passwordreset_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 21, 31, 8, 139394, tzinfo=datetime.timezone.utc)),
        ),
    ]
