# Generated by Django 5.1.7 on 2025-03-30 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_passwordreset_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 19, 2, 30, 752620, tzinfo=datetime.timezone.utc)),
        ),
    ]
